admins = [
    "peter@ghdfoundation.com",
    "kata@ghdfoundation.com",
    "gabor@ghdfoundation.com",
    "admin@ghdfoundation.com",
    "filepdyna@gmail.com",
    "vivien@ghdfoundation.com",
    "maranna6599@gmail.com"
    ]

mentors = [
    {
        "first_name": "Klára",
        "last_name": "Varga Tóth",
        "country_id": 2,
        "email": "tothovaklara@gmail.com",
        "preferred_language_Id": 1,
        "active": True,
    },
    {
        "first_name": "Péter",
        "last_name": "Varga",
        "country_id": 2,
        "email": "vargapepe7@gmail.com",
        "preferred_language_Id": 1,
        "active": True,
    },
    {
        "first_name": "Vojtech",
        "last_name": "Szajkó",
        "country_id": 2,
        "email": "farebneluce@centrum.sk",
        "preferred_language_Id": 1,
        "active": False,
    },
    {
        "first_name": "Ádám",
        "last_name": "Csonka",
        "country_id": 2,
        "email": "adamcsonka77@gmail.com",
        "preferred_language_Id": 1,
        "active": True,
    },
    {
        "first_name": "Gejza",
        "last_name": "Váradi",
        "country_id": 2,
        "email": "gezuvaradi345@gmail.com",
        "preferred_language_Id": 1,
        "active": True,
    },
    {
        "first_name": "Cynthia",
        "last_name": "Ferkóova",
        "country_id": 2,
        "email": "szinti.ferko@gmail.com",
        "preferred_language_Id": 1,
        "active": True,
    },
    {
        "first_name": "Alex",
        "last_name": "Agócs",
        "country_id": 2,
        "email": "alex.agocs.22@gmail.com",
        "preferred_language_Id": 1,
        "active": True,
    },
    {
        "first_name": "Patrik",
        "last_name": "Ferkó",
        "country_id": 2,
        "email": "patrikferko333@gmail.com",
        "preferred_language_Id": 1,
        "active": True,
    },
    {
        "first_name": "Banjámin",
        "last_name": "Gál",
        "country_id": 1,
        "email": "galbeno02@gmail.com",
        "preferred_language_Id": 1,
        "active": False,
    },
    {
        "first_name": "Katalin",
        "last_name": "Kövesdy",
        "country_id": 1,
        "email": "kovesdykata70@gmail.com",
        "preferred_language_Id": 1,
        "active": True,
    },
    {
        "first_name": "Tamás",
        "last_name": "Jocha",
        "country_id": 1,
        "email": "jochatamas19@gmail.com",
        "preferred_language_Id": 1,
        "active": True,
    },
    {
        "first_name": "Ferenc",
        "last_name": "Havlicsek",
        "country_id": 1,
        "email": "kidcatman1992@gmail.com",
        "preferred_language_Id": 1,
        "active": True,
    },
    {
        "first_name": "Attila",
        "last_name": "Oláh",
        "country_id": 1,
        "email": "olaha3716@gmail.com",
        "preferred_language_Id": 1,
        "active": True,
    },
    {
        "first_name": "Bence",
        "last_name": "Zagyi",
        "country_id": 1,
        "email": "z.bence26@gmail.com",
        "preferred_language_Id": 1,
        "active": True,
    },
    {
        "first_name": "Eszter",
        "last_name": "Greskovics",
        "country_id": 1,
        "email": "esztergreskovics@gmail.com",
        "preferred_language_Id": 1,
        "active": False,
    },
    {
        "first_name": "Ágnes",
        "last_name": "Dominik-Suhajda",
        "country_id": 1,
        "email": "agi.ikigai@gmail.com",
        "preferred_language_Id": 1,
        "active": False,
    },
    {
        "first_name": "Szelina",
        "last_name": "Virág",
        "country_id": 1,
        "email": "szelinavirag@gmail.com",
        "preferred_language_Id": 1,
        "active": True,
    },
    {
        "first_name": "Levente",
        "last_name": "Siroki",
        "country_id": 1,
        "email": "sirokilevi123@gmail.com",
        "preferred_language_Id": 1,
        "active": True,
    },
    {
        "first_name": "Toder",
        "last_name": "Bohdan",
        "country_id": 3,
        "email": "bohdantoder7454@gmail.com",
        "preferred_language_Id": 3,
        "active": True,
    },
    {
        "first_name": "Ishtvan",
        "last_name": "Dendeshi",
        "country_id": 3,
        "email": "ishtvan.dendeshi@gmail.com",
        "preferred_language_Id": 3,
        "active": True,
    },
    {
        "first_name": "Nadia",
        "last_name": "Fontosh",
        "country_id": 3,
        "email": "nadiafontos44@gmail.com",
        "preferred_language_Id": 3,
        "active": True,
    },
    {
        "first_name": "Oksana",
        "last_name": "Kuzmanich",
        "country_id": 3,
        "email": "kuzmanichoksana15d@gmail.com",
        "preferred_language_Id": 3,
        "active": True,
    },
    {
        "first_name": "Lyubov",
        "last_name": "Gushtan",
        "country_id": 3,
        "email": "lubahustan@gmail.com",
        "preferred_language_Id": 3,
        "active": True,
    },
    {
        "first_name": "Svitlana",
        "last_name": "Chyryban",
        "country_id": 3,
        "email": "shvidkas@ukr.net",
        "preferred_language_Id": 3,
        "active": True,
    },
    {
        "first_name": "Marianna",
        "last_name": "Logojda",
        "country_id": 3,
        "email": "logojda69@gmail.com",
        "preferred_language_Id": 3,
        "active": True,
    },
    {
        "first_name": "Yevheny",
        "last_name": "Bortek",
        "country_id": 3,
        "email": "jenikck@gmail.com",
        "preferred_language_Id": 3,
        "active": True,
    },
    {
        "first_name": "Volodymyr",
        "last_name": "Bambula",
        "country_id": 3,
        "email": "romanirota@ukr.net",
        "preferred_language_Id": 3,
        "active": True,
    },
    {
        "first_name": "Anzhelika",
        "last_name": "Panchen",
        "country_id": 3,
        "email": "romanirota@ukr.net",
        "preferred_language_Id": 3,
        "active": True,
    },
    {
        "first_name": "Maksym",
        "last_name": "Dzhum",
        "country_id": 3,
        "email": "maximdzhum@gmail.com",
        "preferred_language_Id": 3,
        "active": False,
    },
    {
        "first_name": "Bea",
        "last_name": "Szöllősi",
        "country_id": 1,
        "email": "bea@beltanoda.hu",
        "preferred_language_Id": 3,
        "active": False,
    },
    {
        "first_name": "Kata",
        "last_name": "Gerhard",
        "country_id": 1,
        "email": "kata@beltanoda.hu",
        "preferred_language_Id": 3,
        "active": False,
    }
]

courses = [
    {
        "name": "Tornaľa",
        "description": "Základná škola Ferenca Kazinczyho s vyučovacím jazykom maďarským Tornaľa (hu:Kazinczy Ferenc Magyar Tanítási Nyelvű Alapiskola Tornalja)",
        "country_id": 2,
        "active": True,
    },
    {
        "name": "Gemer",
        "description": "Základná škola s vyučovacím jazykom maďarským - Alapiskola (hu: Sajógömöri Magyar Tannyelvű Alapiskola)",
        "country_id": 2,
        "active": True,
    },
    {
        "name": "Gemerská Ves",
        "description": "Základná škola - Alapiskola Gemerská Ves",
        "country_id": 2,
        "active": True,
    },
    {
        "name": "Lenartovce 1",
        "description": "Základná škola s materskou školou s vyučovacím jazykom maďarským Lenartovce (hu: Magyar Tanítási nyelvű Alapiskola és Óvoda Sajólénártfalva",
        "country_id": 2,
        "active": True,
    },
    {
        "name": "Lenartovce 2",
        "description": "Základná škola s materskou školou s vyučovacím jazykom maďarským Lenartovce (hu: Magyar Tanítási nyelvű Alapiskola és Óvoda Sajólénártfalva",
        "country_id": 2,
        "active": True,
    },
    {
        "name": "Lenartovce 3",
        "description": "Základná škola s materskou školou s vyučovacím jazykom maďarským Lenartovce (hu: Magyar Tanítási nyelvű Alapiskola és Óvoda Sajólénártfalva",
        "country_id": 2,
        "active": True,
    },
    {
        "name": "Lenartovce 4",
        "description": "Základná škola s materskou školou s vyučovacím jazykom maďarským Lenartovce (hu: Magyar Tanítási nyelvű Alapiskola és Óvoda Sajólénártfalva",
        "country_id": 2,
        "active": True,
    },
    {
        "name": "Lenartovce 5",
        "description": "Základná škola s materskou školou s vyučovacím jazykom maďarským Lenartovce (hu: Magyar Tanítási nyelvű Alapiskola és Óvoda Sajólénártfalva",
        "country_id": 2,
        "active": True,
    },
    {
        "name": "Barca 1",
        "description": "Základná škola s vyučovacím jazykom maďarským Barca (hu: Magyar Tanítási Nyelvű Alapiskola, Baraca)",
        "country_id": 2,
        "active": True,
    },
    {
        "name": "Barca 2",
        "description": "Základná škola s vyučovacím jazykom maďarským Barca (hu: Magyar Tanítási Nyelvű Alapiskola, Baraca)",
        "country_id": 2,
        "active": True,
    },
    {
        "name": "Uzovská Panica 1",
        "description": "Základná škola s vyučovacím jazykom maďarským Uzovská Panica (hu: Magyar Tanítási Nyelvű Alapiskola Uzapanyit",
        "country_id": 2,
        "active": True,
    },
    {
        "name": "Uzovská Panica 2",
        "description": "Základná škola s vyučovacím jazykom maďarským Uzovská Panica (hu: Magyar Tanítási Nyelvű Alapiskola Uzapanyit",
        "country_id": 2,
        "active": True,
    },
    {
        "name": "Bátonyterenye Tanoda",
        "description": "Bátonyterenyei Tanoda",
        "country_id": 1,
        "active": True,
    },
    {
        "name": "Erdőkövesd",
        "description": "Boglyas Kuckó",
        "country_id": 1,
        "active": True,
    },
    {
        "name": "Bátonyterenye Óvoda",
        "description": "Bátonyterenyei Városi Óvoda",
        "country_id": 1,
        "active": False,
    },
    {
        "name": "Hegymeg",
        "description": "Hegymegért Egyesület",
        "country_id": 1,
        "active": True,
    },
    {
        "name": "Homrogd",
        "description": "Homrogd közösségi és esély ház",
        "country_id": 1,
        "active": True,
    },
    {
        "name": "Lucfalva",
        "description": "Nógrád Megyei Cigány Kisebbségi Képviselők és Szószólók Szövetsége (NMCKKSZSZ)",
        "country_id": 1,
        "active": True,
    },
    {
        "name": "Mátraverebély",
        "description": "Nógrád Megyei Cigány Kisebbségi Képviselők és Szószólók Szövetsége (NMCKKSZSZ)",
        "country_id": 1,
        "active": True,
    },
    {
        "name": "UMTK 1",
        "description": "Ökumenikus Segélyszervezet - Ukrajnai Menekülteket Támogató Központ",
        "country_id": 1,
        "active": False,
    },
    {
        "name": "UMTK 2",
        "description": "Ökumenikus Segélyszervezet - Ukrajnai Menekülteket Támogató Központ",
        "country_id": 1,
        "active": False,
    },
    {
        "name": "Zugliget",
        "description": "Fővárosi Önkormányzat Kútvölgyi úti Idősek Otthona Zugligeti úti telephely",
        "country_id": 1,
        "active": True,
    },
    {
        "name": "Tomor",
        "description": "Romama",
        "country_id": 1,
        "active": True,
    },
    {
        "name": "Uzhhorod Lyceum",
        "description": "Uzhhorod Lyceum Intellect",
        "country_id": 3,
        "active": True,
    },
    {
        "name": "Uzhhorod Gymn 14",
        "description": "Uzhhorod Gymnasium No. 14",
        "country_id": 3,
        "active": True,
    },
    {
        "name": "Tur'ya Pasika School",
        "description": "Tur'ya Pasitske Secondary School of the Turya Remeta Council",
        "country_id": 3,
        "active": True,
    },
    {
        "name": "Tur'ya Pasika Center",
        "description": "Tur'ya Pasika Roma Community Center",
        "country_id": 3,
        "active": True,
    },
    {
        "name": "Berehove",
        "description": "Berehove Gymnasium No. 7 ‘Opre Roma’",
        "country_id": 3,
        "active": True,
    },
    {
        "name": "Zolotonosha",
        "description": "NGO ‘Romani Rota’",
        "country_id": 3,
        "active": True,
    },
    {
        "name": "Odesa",
        "description": "CF ‘Planet of Good People’",
        "country_id": 3,
        "active": False,
    },
    {
        "name": "Belvárosi Tanoda",
        "description": "Belvárosi Tanoda Alapítványi Gimnázium, Budapest",
        "country_id": 1,
        "active": False,
    }
    ]

mentor-course-pairs = [
    (1,  1),  (2,  2),  (3,  2),  (4,  3),  (5,  4), 
    (5,  5),  (5,  6),  (5,  7),  (5,  8),  (6,  9), 
    (7,  9),  (6,  10), (7,  10), (8,  11), (8,  12), 
    (9,  13), (10, 14), (10, 15), (11, 16), (12, 17), 
    (13, 18), (14, 19), (15, 20), (16, 20), (15, 21), 
    (16, 21), (17, 22), (18, 23), (19, 24), (20, 25), 
    (21, 26), (22, 26), (23, 26), (21, 27), (24, 28), 
    (25, 28), (26, 29), (27, 29), (28, 29), (29, 30),
    (30, 31), (31, 31)
    ]