const mentorStudentTitle = {
    en: "Manage students",
    hu: "Diákok kezelése",
    ua: "Керування студентами"
}

const languageData = {
    en: {
        first_name: "First name",
        last_name: "Last name",
        country: "Country",
        select_a_country: "--Select a country--",
        hungary: "Hungary",
        slovakia: "Slovakia",
        ukraine: "Ukraine",
        birthyear: "Birthyear",
        gender: "Gender",
        select_a_gender: "--Select a gender--",
        male: "Male",
        female: "Female",
        non_binary: "Non-binary",
        active: "Active",
        courses: "Course(s)",
        submit: "Submit",
        cancel: "Cancel",
        add: "Add",
        edit: "Edit",
    },
    hu: {
        first_name: "Keresztnév",
        last_name: "Családnév",
        country: "Ország",
        select_a_country: "--Válassz országot--",
        hungary: "Magyarország",
        slovakia: "Szlovákia",
        ukraine: "Ukrajna",
        birthyear: "Születési év",
        gender: "Nem",
        select_a_gender: "--Válassz nemet--",
        male: "Fiú",
        female: "Lány",
        non_binary: "Nem-bináris",
        active: "Aktív",
        courses: "Kurzusok",
        submit: "Beküld",
        cancel: "Mégsem",
        add: "Hozzáad",
        edit: "Szerkeszt",
    },
    ua: {
        first_name: "Ім'я",
        last_name: "Прізвище",
        country: "Країна",
        select_a_country: "--Виберіть країну--",
        hungary: "Угорщина",
        slovakia: "Словаччина",
        ukraine: "Україна",
        birthyear: "Рік народження",
        gender: "Стать",
        select_a_gender: "--Виберіть стать--",
        male: "чоловічий",
        female: "жінка",
        non_binary: "недвійковий",
        active: "Активний",
        courses: "Курс(и)",
        submit: "Надіслати",
        cancel: "Скасувати",
        add: "Додати",
        edit: "Редагувати",
    }
}
