const storyTitle = {
    en: "Story of the month",
    hu: "A hónap sztorija",
    ua: "Історія місяця"
}

const languageData = {
    en: {
        mentor: "Mentor",
        year_month: "Year / Month",
        course: "Course",
        story: "Story",
        january: "January",
        february: "February",
        march: "March",
        april: "April",
        may: "May",
        june: "June",
        july: "July",
        august: "August",
        september: "September",
        october: "October",
        november: "November",
        december: "December",
    },
    hu: {
        mentor: "Mentor",
        year_month: "Év / Hónap",
        course: "Kurzus",
        story: "Sztori",
        january: "Január",
        february: "Február",
        march: "Március",
        april: "Április",
        may: "Május",
        june: "Június",
        july: "Július",
        august: "Augusztus",
        september: "Szeptember",
        october: "Október",
        november: "November",
        december: "December",
    },
    ua: {
        mentor: "Наставник",
        year_month: "Пік / Місяць",
        course: "Курс",
        story: "Історія",
        january: "Січень",
        february: "Лйутий",
        march: "Березень",
        april: "Квітень",
        may: "Травень",
        june: "Червень",
        july: "Ліпень",
        august: "Серпень",
        september: "Вересень",
        october: "Жовтень",
        november: "Лістопад",
        december: "Ґрудень",
    },
}